// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVCsN6rtJMCHHrwsnl3JHO8Vj0Tw0aYZk',
    appId: '1:449390386374:web:03598b9c78a52fac6e8bc7',
    messagingSenderId: '449390386374',
    projectId: 'techchefapp',
    authDomain: 'techchefapp.firebaseapp.com',
    storageBucket: 'techchefapp.firebasestorage.app',
    measurementId: 'G-NK454SCSLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLeXbDh4-o8j8yG_5yZGQb2fZHsfgJzPE',
    appId: '1:449390386374:android:ad5bf17a067b1f856e8bc7',
    messagingSenderId: '449390386374',
    projectId: 'techchefapp',
    storageBucket: 'techchefapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2UMcYRvjVF9RKjWb9MSIpFgurIMdPTBQ',
    appId: '1:449390386374:ios:7d54d168aa9b21b56e8bc7',
    messagingSenderId: '449390386374',
    projectId: 'techchefapp',
    storageBucket: 'techchefapp.firebasestorage.app',
    iosBundleId: 'com.example.aplicativofuncional',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2UMcYRvjVF9RKjWb9MSIpFgurIMdPTBQ',
    appId: '1:449390386374:ios:7d54d168aa9b21b56e8bc7',
    messagingSenderId: '449390386374',
    projectId: 'techchefapp',
    storageBucket: 'techchefapp.firebasestorage.app',
    iosBundleId: 'com.example.aplicativofuncional',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVCsN6rtJMCHHrwsnl3JHO8Vj0Tw0aYZk',
    appId: '1:449390386374:web:b038c78e763d1dd46e8bc7',
    messagingSenderId: '449390386374',
    projectId: 'techchefapp',
    authDomain: 'techchefapp.firebaseapp.com',
    storageBucket: 'techchefapp.firebasestorage.app',
    measurementId: 'G-3WJ6SBM45P',
  );
}
